### ISSUE TITLE
Duplicates in race conditions between multiple processes

### ISSUE THREAD

**Issue by dude0001** [ardalis/DDD-NoDuplicates#1]
I'm struggling to understand which of these solutions, if any, would work in a scenario where you are scaling up multiple processes that can create or update the same entity type in a document DB. Am I correct that these solutions are targeted at a single-threaded process (or maybe a single process multi-threaded with some added locking code) and not a multi-process solution? Or am I missing something? The DB constraint, which as you said, is too expensive for my case.  I have multiple processes that create and store entities in a central document DB and I have a similar business rule to preventing duplicates I need to enforce.

**Comment by ardalis** [comment]
Yes, the in-code approaches assume a single thread or some form of locking. In your scenario you would have options:
1) Use a database option - you said this won't work
2) Use a single service for performing this operation - essentially force it to be single-threaded. Could use a command queue to feed the service. May not scale.
3) Use some kind of distributed transaction coordinator
4) Go for eventual consistency; let duplicates happen but detect them via another process and roll them back or otherwise act on them. Perhaps name changes aren't permanent until they've persisted for some period of time.

That's off the top of my head - does any of that sound helpful?

**Comment by dude0001** [comment]
Thank you for the reply and the article. I very much enjoyed looking through the repo even though it doesn't directly apply to my problem at hand. I am pursuing DTC currently so it sounds like I am in the right track and not completely missing something.
